# Generated by Django 3.1.8 on 2021-07-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210701_1431'),
        ('customers', '0002_auto_20210701_1418'),
    ]

    operations = [
    ]
