# Generated by Django 3.1.8 on 2021-07-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210701_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
